[package]
name = "site-generator"
version = "0.1.0"

[workspace]
members = [
  "site-generator-core",
  "site-generator-derive",
]

[dependencies]
clap = { version = "4.1.11", features = ["derive"] }
#site-generator-core = { path = "site-generator-core" }
site-generator-derive = { path = "site-generator-derive" }
maud = "0.24.0"
darling = "0.20.0"
syn = "2.0.15"
chrono = "0.4.24"
markdown = "1.0.0-alpha.9"
