[package]
name = "site-generator"
version = "0.1.0"

[workspace]
members = [
  "site-generator-derive",
]

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
site-generator-derive = { path = "site-generator-derive" }
maud = "0.26.0"
darling = "0.20.8"
syn = "2.0.58"
chrono = "0.4.37"
markdown = "1.0.0-alpha.16"
